# Generated by Django 3.0 on 2021-02-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(db_column='title', max_length=100)),
                ('empname', models.TextField(db_column='description', max_length=1000)),
                ('asset', models.CharField(db_column='author', max_length=100)),
            ],
        ),
    ]
