# Generated by Django 3.0 on 2021-02-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset',
            field=models.CharField(db_column='asset', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='empid',
            field=models.CharField(db_column='empid', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='empname',
            field=models.CharField(db_column='empname', max_length=100),
        ),
    ]
